# Generated by Django 3.2 on 2021-04-20 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, null=True, unique=True)),
                ('token_expire_time', models.DateTimeField(null=True)),
                ('customer_id', models.CharField(max_length=32, unique=True)),
                ('customer_name', models.CharField(default='', max_length=30)),
                ('customer_email', models.CharField(max_length=30, unique=True)),
                ('customer_pass', models.CharField(max_length=32)),
                ('customer_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'db_customer',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_author', models.CharField(max_length=64)),
                ('book_title', models.CharField(max_length=128)),
                ('book_description', models.CharField(default='', max_length=512)),
                ('book_poster_image', models.CharField(default='', max_length=512)),
                ('book_created_at', models.DateTimeField(auto_now_add=True)),
                ('book_updated_at', models.DateTimeField(auto_now_add=True)),
                ('customer_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            options={
                'db_table': 'db_book',
                'ordering': ['book_updated_at'],
            },
        ),
    ]
