# Generated by Django 3.2 on 2021-04-21 02:31

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_book_user_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_poster_image',
            field=models.ImageField(blank=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
