# Generated by Django 3.2 on 2021-04-21 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20210421_0231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('user_target', 'book_author', 'book_title')},
        ),
    ]
